/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { SlashCommand, CommandCategory } from './types.js';

const AGENTS_FILENAME = 'AGENTS.md';

const MAX_LINES_PER_FILE = 200;
const MAX_BYTES_PER_FILE = 16_000;
const SAMPLE_FILES = [
  'package.json',
  'README.md',
  'tsconfig.json',
  'pyproject.toml',
  'Cargo.toml',
  'go.mod',
  'pom.xml',
  'build.gradle',
  'src/main',
  'src/index',
  'app/main',
  'cmd',
  'index.js',
  'index.ts',
  'main.py',
];

async function readSample(root: string, rel: string): Promise<string | null> {
  const full = path.join(root, rel);
  if (!existsSync(full)) return null;
  try {
    const stat = await fs.stat(full);
    if (!stat.isFile() || stat.size > MAX_BYTES_PER_FILE) return null;
    const content = await fs.readFile(full, 'utf8');
    const lines = content.split('\n');
    if (lines.length > MAX_LINES_PER_FILE) {
      return lines.slice(0, MAX_LINES_PER_FILE).join('\n') + '\n… (truncated)';
    }
    return content;
  } catch {
    return null;
  }
}

async function detectProjectType(root: string): Promise<{ name: string; description: string; stack: string }> {
  if (existsSync(path.join(root, 'package.json'))) {
    return { name: 'Node.js project', description: 'Node/JavaScript package', stack: 'JavaScript / TypeScript' };
  }
  if (existsSync(path.join(root, 'pyproject.toml')) || existsSync(path.join(root, 'setup.py'))) {
    return { name: 'Python project', description: 'Python package', stack: 'Python' };
  }
  if (existsSync(path.join(root, 'Cargo.toml'))) {
    return { name: 'Rust project', description: 'Rust crate', stack: 'Rust' };
  }
  if (existsSync(path.join(root, 'go.mod'))) {
    return { name: 'Go project', description: 'Go module', stack: 'Go' };
  }
  if (existsSync(path.join(root, 'pom.xml')) || existsSync(path.join(root, 'build.gradle'))) {
    return { name: 'JVM project', description: 'Java/Kotlin application', stack: 'Java/Kotlin' };
  }
  return { name: 'Project', description: 'A code project', stack: 'Unknown' };
}

export const initCommand: SlashCommand = {
  name: 'init',
  altName: 'setup',
  description: 'Scan the project and create an AGENTS.md memory file with a starter brief',
  category: 'general' as CommandCategory,
  keywords: ['init', 'setup', 'bootstrap', 'memory', 'agents', 'project'],
  action: async (_context, args) => {
    const root = process.cwd();
    const fileName = args?.trim() || AGENTS_FILENAME;
    const target = path.join(root, fileName);

    if (existsSync(target) && args?.trim() !== '--force') {
      return {
        type: 'message',
        messageType: 'info',
        content: `${fileName} already exists. Re-run with \`/init --force\` to overwrite.`,
      };
    }

    const project = await detectProjectType(root);
    const samples: string[] = [];
    for (const candidate of SAMPLE_FILES) {
      const content = await readSample(root, candidate);
      if (content) {
        samples.push(`### ${candidate}\n\`\`\`\n${content.trim()}\n\`\`\``);
      }
      if (samples.length >= 3) break;
    }

    const timestamp = new Date().toISOString();
    const lines: string[] = [
      `# ${project.name} — A-Coder brief`,
      '',
      `_Generated by a-coder-cli /init on ${timestamp}._`,
      '',
      `## Stack`,
      '',
      `- Type: ${project.description}`,
      `- Stack: ${project.stack}`,
      '',
      '## Working conventions',
      '',
      '- Read files before editing them.',
      '- Prefer minimal, surgical changes that match the existing style.',
      '- Run the project tests after any non-trivial change.',
      '- When the user asks to "build", make file edits, run commands, and verify the result before claiming success.',
      '',
    ];
    if (samples.length > 0) {
      lines.push('## Project snippets');
      lines.push('');
      lines.push('The following excerpts give a quick feel for the codebase. Update this file as the project grows.');
      lines.push('');
      lines.push(...samples);
      lines.push('');
    }
    lines.push('## Custom instructions');
    lines.push('');
    lines.push('_Add anything the agent should always remember about this project (architecture decisions, preferred libraries, deployment notes, etc.)._');
    lines.push('');

    try {
      await fs.writeFile(target, lines.join('\n'), 'utf8');
    } catch (err) {
      return {
        type: 'message',
        messageType: 'error',
        content: `Failed to write ${fileName}: ${(err as Error).message}`,
      };
    }
    return {
      type: 'message',
      messageType: 'info',
      content: `Wrote ${fileName} (${lines.length} lines). It will be auto-loaded as project context on future prompts.`,
    };
  },
};
