// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const INCEPTION_MODELS = {
	"mercury-2": {
		id: "mercury-2",
		name: "Mercury 2",
		api: "openai-completions",
		provider: "inception",
		baseUrl: "https://api.inceptionlabs.ai/v1",
		compat: {"maxTokensField":"max_tokens","supportsDeveloperRole":false,"supportsReasoningEffort":false,"supportsStore":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.25,
			output: 0.75,
			cacheRead: 0.025,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 50000,
	} satisfies Model<"openai-completions">,
	"mercury-2.5": {
		id: "mercury-2.5",
		name: "Mercury 2.5",
		api: "openai-completions",
		provider: "inception",
		baseUrl: "https://api.inceptionlabs.ai/v1",
		compat: {"maxTokensField":"max_tokens","supportsDeveloperRole":false,"supportsReasoningEffort":false,"supportsStore":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.04,
			output: 0.15,
			cacheRead: 0.004,
			cacheWrite: 0,
		},
		contextWindow: 260000,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
} as const;
