// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openadapter.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const OPENADAPTER_MODELS: ModelCatalog<typeof values, "openadapter"> =
	flattenModelCatalog("openadapter", values);
